# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: coolsharp
email: coolsharp@gmail.com
description:  coolsharp의 블로그 입니다. 유용하고 좋은 내용을 많은 분들과 공유하기 위한 페이지 입니다.
baseurl: "/coolsharp" # the subpath of your site, e.g. /blog
url: "http://coolsharp.github.com" # the base hostname & protocol for your site
twitter_username: coolsharp
github_username:  coolsharp

# Build settings
markdown: kramdown
